### ISSUE TITLE
Assets serving inconsistency when testing package/packages

### ISSUE THREAD

**Issue by ShockiTV** [xolvio/meteor-jasmine#305] opened 2015-12-07 16:23 UTC
Hello,

when using velocity-cli to test package/packages, there is inconsistency in assets serving path

velocity test-packages  --port 3500
```
http://localhost:3500/packages/myapp_package/tests/assets/myasset.xml
```
velocity test-package myapp:package --port 3500
```
http://localhost:3500/packages/local-test_myapp_package/tests/assets/myasset.xml
```
So we are not able to test per package correctly.

**Comment by Sanjo** [comment] 2015-12-07 17:02
Hi, that's something that you need to report to meteor/meteor directly.
I'm not sure what you want to achieve, but don't read the file directly from the file system. Use Assets.getText or hardcode the XML file in a JavaScript file by assigning it to a variable.

**Closed by Sanjo** 2015-12-07 17:02 UTC

**Comment by ShockiTV** [comment] 2015-12-07 17:21
Hi, our usecase is that we have method which downloads specific file and than we are importing it to mongo. To test it we decided to use package asset serving functionality. But it is not always served on same path, depending on how we run the tests.
As I did not studied deeper how velocity-cli calls meteor commands, I expected it to be somehow related more to testing framework than to meteor itself.
Using direct Asset object would not help with download functionality testing much.
```
api.addAssets([
        "tests/assets/myasset.xml",
    ], 'client');
```
Regards
Robert

**Comment by Sanjo** [comment] 2015-12-07 23:25
A workaround could be to dynamically generate the file url by checking for the existence of `Package['local-test_myapp_package']` and `Package['myapp_package']` and based on this info you know what the current package name is.

The issue is in the meteor core in the part that implements the `meteor test-packages` command. That's what velocity-cli is using.
