### ISSUE TITLE
Async tests stop executing after first one

### ISSUE THREAD

**Issue by MichaelHirn** [xolvio/meteor-jasmine#253] opened 2015-07-23 19:05 UTC
This problems seems to be the same as described in #236 . I am using `sanjo:jasmine@0.14.0` and meteor at `1.1.0.2`. 

The problem is, that after the first async test (`it` block) no other async test blocks - even if they are in different `describe` blocks, get executed (do not appear on the html-reporter).

So here is a code example

``` coffeescript
describe 'update', ->

      it 'updates correctly with single argument', (done) ->
        someDbQuery (error, result) ->
          before = result?.row
          anotherDbQuery (error, result) ->
              after = result?.rows
              expect(before.length).toEqual(after.length)
              done()

      # this block will be never executed
      it 'updates correctly with multiple arguments', (done) ->
        someDbQuery (error, result) ->
          anotherDbQuery (error, result) ->
            expect(result?.rows.length).toBe(3)
            done()

      # nor will any other async tests that follow from here on down, ever if they are in completely different describe blocks
      # sync tests work just fine how ever
```

For a working error example you can check out [this branch](https://github.com/storeness/meteor-postgres/tree/async-test-bug). The README also contains the command to to run the tests.

**Comment by Sanjo** [comment] 2015-07-23 20:38
The underlying issue is https://github.com/Sanjo/meteor-jasmine/issues/239. I'm going to release a new version with a fix.

**Comment by MichaelHirn** [comment] 2015-07-23 20:42
:+1: great, we are looking forward to it

**Comment by Sanjo** [comment] 2015-07-23 20:51
Fixed with 0.15.0 that is now available.

**Comment by MichaelHirn** [comment] 2015-07-23 21:11
Updated [the branch](https://github.com/storeness/meteor-postgres/tree/async-test-bug) now with the latest version `0.15.0` but `done` seems to be undefined now? Did I miss something obvious - I checked the latest commit change, though I could not understand why it is broken now. Anyways, the branch is updated, you should see the error.

**Comment by Sanjo** [comment] 2015-07-23 21:14
I will check it now.

**Comment by Sanjo** [comment] 2015-07-23 21:19
I did something wrong and missed the error. Will fix it now.

**Comment by Sanjo** [comment] 2015-07-23 21:40
I've released a fix 0.15.1. But it turns out that you still need to bind your callback manually to the Fiber. See the new section: https://github.com/Sanjo/meteor-jasmine/blob/master/README.md#async-tests. Let me know if you have any questions or still problems after doing this.

**Comment by MichaelHirn** [comment] 2015-07-23 21:59
Thank you. Tests are working just fine now with `Meteor.bindEnvironment`. :+1:

**Comment by Alino** [comment] 2015-10-15 14:14
I also have this behavior on Meteor version ```1.2.0.2``` and ```sanjo:jasmine@0.20.2```

this is my code

```coffeescript
describe 'createMasterProduct', ->
  describe 'downloadFile', ->
    it 'should download the file to filesystem', (done) ->
      url = 'https://www.google.sk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
      destination = "#{Kuknito.projectPath}/.images/test/"

      passTest = (downloadPath) ->
        expect(downloadPath).toBeDefined
        done()

      failTest = (error) ->
        expect(error).toBeUndefined

      downloadFile(url, destination)
      .then(passTest)
      .catch(failTest)

    it 'should catch an error if the file is unreachable', (done) ->
      url = 'https://www.google.sk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.kokotpica'
      destination = "#{Kuknito.projectPath}/.images/test/"

      passTest = (downloadPath) ->
        console.log downloadPath
        expect(downloadPath).toBeDefined

      failTest = (error) ->
        console.log 'fail mothafucka'
        console.log error
        if error then e = true
        expect(e).toBe true
        done()

      downloadFile(url, destination)
      .then(passTest)
      .catch(failTest)
```

only first test goes to html reporter.

I am testing this inside a package with this command:
```velocity test-package kuknito:admin --port 3500 --settings settings.json```

I am also experiencing duplicate server integration in html reporter here is a screenshot what I mean:
![duplicateenv](https://cloud.githubusercontent.com/assets/763194/10516290/dbc084d2-7357-11e5-9a39-9adc07f3fa2c.png)

**Comment by Sanjo** [comment] 2015-10-15 21:10
@Alino Have you looked in the browser console for errors? You don't call done() in the fail handler of the first test. I cannot help you more without a reproduce app. Let me know if me suggestions helped.

**Comment by Alino** [comment] 2015-10-15 21:50
@Sanjo thank you for reply. I tried with done() even in fail code blocks - didn't help.
Here is a reproduce app I just created https://github.com/Alino/meteorJasmineAsyncBug
There is also that bug with duplicate server integration showing up, I suspect it happens maybe because of the test file location (tests/server)

**Comment by Alino** [comment] 2015-10-19 09:41
could anyone with the rights, reopen this issue please?

**Comment by ShockiTV** [comment] 2015-11-22 13:01
+1

**Comment by fuckthescript** [comment] 2015-11-22 20:55
+1 same issue with bluebird
@Alino have you solved it?

**Comment by Sanjo** [comment] 2015-11-23 09:47
@Alino In your tests the toBeDefined and toBeUndefined need braces. Otherwise it is not a function call. Have you tried if the JavaScript equivalent works? Is this only a CoffeeScript issue?

**Comment by Alino** [comment] 2015-11-23 10:12
@fuckthescript not yet, I had to disable my async tests, because it is blocking all other tests...

@Sanjo good point, I tried to add the braces in this commit
https://github.com/Alino/meteorJasmineAsyncBug/tree/8dd8f5588d53ae4afb1dba81ea89fd8da4db0eca

I even tried to put the tests to javascript in this commit
https://github.com/Alino/meteorJasmineAsyncBug/tree/b1a495e87690af70a224212a36ff4239dce49443

the issue still remains :(

**Comment by fuckthescript** [comment] 2015-11-24 22:17
I think it will be some problem between Bluebird and velocity, velocity can't handle bluebird's promises very well. I am still trying to find some solution.

**Comment by Sanjo** [comment] 2015-11-25 04:44
Why do you use Bluebird, when there is already the promise Meteor package? If it is a high priority for you to get that fixed, please use our service: http://xolv.io/services/meteor-testing-support/.

**Comment by Alino** [comment] 2015-12-08 17:18
I replaced Bluebird with Meteor Promise ES6 polyfill and it works. Thank you Maybe this issue should be closed because it is specific for Bluebird.

**Comment by Sanjo** [comment] 2015-12-08 21:35
Cool. It seems that Meteor has problems when another Promise providing library is used in addition to the promise meteor package, that is a core dependency.

**Closed by Sanjo** 2015-12-08 21:35 UTC
Labels: bug, server-integration-mode
